insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (1, 'Garry', 'Woodall', 648, 918, 11);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (2, 'Giorgio', 'Varvell', 148, 912, 2);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (3, 'Florida', 'Schmuhl', 219, 671, 1);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (4, 'Maryann', 'Stoddart', 389, 654, 3);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (5, 'Kaine', 'Barenskie', 182, 591, 12);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (6, 'Lorettalorna', 'DelaField', 690, 604, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (7, 'Vance', 'Band', 974, 176, 10);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (8, 'Molli', 'Barkly', 25, 704, 1);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (9, 'Cassy', 'Letteresse', 452, 655, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (10, 'Gertie', 'Courson', 593, 458, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (11, 'Linzy', 'Maiden', 764, 656, 4);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (12, 'Eziechiele', 'Trevallion', 425, 731, 2);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (13, 'Jasen', 'Schimon', 410, 314, 11);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (14, 'Gabbey', 'Dury', 587, 776, 5);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (15, 'Lilian', 'McAdam', 288, 793, 1);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (16, 'Cyrus', 'Scherer', 901, 317, 11);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (17, 'Leland', 'Juszczak', 927, 512, 6);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (18, 'Trever', 'Meadmore', 310, 361, 4);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (19, 'Dene', 'Milliere', 501, 995, 10);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (20, 'Alaric', 'Gulc', 911, 55, 3);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (21, 'Yevette', 'Lydford', 763, 207, 4);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (22, 'Noak', 'Gumery', 870, 51, 3);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (23, 'Welch', 'Draysay', 617, 646, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (24, 'Myrle', 'Kilalea', 472, 933, 12);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (25, 'Martie', 'Lortzing', 476, 213, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (26, 'Cecil', 'Load', 989, 372, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (27, 'Ermanno', 'Kincaid', 891, 756, 5);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (28, 'Fredelia', 'Buse', 636, 125, 8);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (29, 'Andonis', 'Partrick', 284, 331, 1);
insert into Customers (customerId, first_name, last_name, accumulatedPoints, usedPoints, beginMonth) values (30, 'Moishe', 'Bray', 748, 436, 5);

insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (1, 'North', 'Burgils');
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (2, 'North', 'Spago');
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (3, 'North', 'Maxican Grills', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (4, 'North', 'The Gourmet Kitchen', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (5, 'North', 'Pink Sugar', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (6, 'North', 'Lord Of Fries', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (7, 'North', 'Thai Me Up Restaurant', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (8, 'North', 'Pho Shizzle', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (9, 'North', 'Ninja Akasaka', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (10, 'South', 'Chill Out', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (11, 'South', 'The Lockhart', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (12, 'South', 'Garden of Eat', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (13, 'South', 'Pies n Tighs', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (14, 'South', 'Dough Doughnuts', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (15, 'South', 'Pita Pans', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (16, 'South', 'Pot Au Feu', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (17, 'South', 'Duke Seafood', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (18, 'South', 'The French Gourmet', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (19, 'East', 'Little Pleasures', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (20, 'East', 'Planet O The Crepes', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (21, 'East', 'The Daily Cut', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (22, 'East', 'Wish You Were Beer', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (23, 'East', 'Burger & Beer Joint', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (24, 'East', 'Daily Grill', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (25, 'East', 'Hot & Crusty', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (26, 'West', 'The Deck', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (27, 'West', 'Waterbar Restaurant', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (28, 'West', 'Brewed Awakening', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (29, 'West', 'Mamas Fish House', 10);
insert into Restaurant (restaurantId, area, name, minSpendingAmt) values (30, 'West', 'The Egg & Us', 10);
